spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.37.69:3306/work_at?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: workatworkat
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-work-at
  redis:
    host: 34.64.37.69
    port: 6379
    password: workat@1234

external:
  kakaoOauth:
    redirect-url: "http://localhost:5050/login"

resources:
  upload-folder: /home/work_at_tour/images
  upload-uri: /uploaded
  profile-upload-folder: /profile_images
