spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work_at?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-work-at
  redis:
    host: localhost
    port: 6379
    password: password
  mail:
    host: smtp.gmail.com
    port: 587
    username: workat.test.mail@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

external:
  kakaoOauth:
    clientId: "7052acd04b3385c80fac9bb40d8b5a32"
  tour-api:
    big-data:
      "2scFfN6uVjhuRcXrj1DgGjslYn0wYJc7kvCOHHwOI/0kr1sjf2OqLLjq5SvCt3jKyr4JPHr/K3QGuXhvv6HYlQ=="

jwt:
  secret: But_man_is_not_made_for_defeat,_A_man_can_be_destroyed_but_not_defeated

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

resources:
  upload-folder: /Users/work_at_tour/images
  upload-uri: /uploaded
  profile-upload-folder: /profile_images
