spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.37.69:3306/work_at?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: workatworkat
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-work-at
  redis:
    host: 34.64.37.69
    port: 6379
    password: workat@1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: work.at.tour@gmail.com
    password: ${EMAIL_PASSWORD}

external:
  kakaoOauth:
    redirect-url: "http://workat.o-r.kr/login"

resources:
  upload-folder: /home/work_at_prod/images
  upload-uri: /uploaded
  profile-upload-folder: /profile_images
