spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

external:
  kakaoOauth:
    clientId: "7052acd04b3385c80fac9bb40d8b5a32"
  tour-api:
    big-data:
      "2scFfN6uVjhuRcXrj1DgGjslYn0wYJc7kvCOHHwOI/0kr1sjf2OqLLjq5SvCt3jKyr4JPHr/K3QGuXhvv6HYlQ=="

jwt:
  secret: JWT_SECRET_KEY

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5
