spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.37.69:3306/work_at?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: workatworkat
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-work-at
  redis:
    host: 34.64.37.69
    port: 6379
    password: workat@1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: work.at.tour@gmail.com
    password: ${EMAIL_PASSWORD}

server:
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
  http2:
    enabled: true

external:
  kakaoOauth:
    redirect-url: "https://workat.o-r.kr/login"

resources:
  images:
    cafe: /images/cafe_images
    restaurant:
      korea: /images/food_images/k_food
      china: /images/food_images/c_food
      japan: /images/food_images/j_food
      wastern: /images/food_images/w_food
      etc: /images/food_images/etc_food
  upload-folder: /home/work_at_prod/images
  upload-uri: /uploaded
  profile-upload-folder: /profile_images
