spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work_at?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      pool-name: pool-work-at
  redis:
    host: localhost
    port: 6379
    password: password

  external:
    kakaoOauth:
      redirect-url: "http://localhost:5050/login"
