name: Dev Deploy Workflow

on:
  push:
    branches:
      - develop

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --info clean build
        
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push the Docker image for develop deployment
        run: |
          docker build -f ./Dockerfile.dev --tag ${{secrets.DOCKER_USERNAME}}/workat:dev .
          docker push ${{secrets.DOCKER_USERNAME}}/workat:dev
        if: contains(github.ref, 'develop')
