name: git-action

on:
  pull_request:
    branches:
      - develop

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --info clean build

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/workat:dev .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/workat:dev
        if: contains(github.ref, 'develop')
